plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
      spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
    'react-ga@^3.3.0':
        dependencies:
            prop-types: '*'
    'vite-plugin-checker@^0.4.6':
        dependencies:
            optionator: '*'
