plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
      spec: '@yarnpkg/plugin-typescript'

npmScopes:
    myspooot:
        npmAlwaysAuth: true
        npmAuthToken: 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
        npmRegistryServer: https://npm.pkg.github.com/

yarnPath: .yarn/releases/yarn-3.1.1.cjs
